// Generated by CoffeeScript 1.3.3
(function() {

  define(function(require, exports, module) {
    var DIVIDER_POSITION, MENU_ENTRY_POSITION, PANEL_POSITION, PATH_TO_JASMINE, commands, css, ext, filelist, fs, ide, markup, menus, noderunner, panels;
    ide = require('core/ide');
    ext = require('core/ext');
    menus = require('ext/menus/menus');
    noderunner = require('ext/noderunner/noderunner');
    commands = require('ext/commands/commands');
    fs = require('ext/filesystem/filesystem');
    panels = require('ext/panels/panels');
    markup = require('text!ext/jasmine/jasmine.xml');
    filelist = require('ext/filelist/filelist');
    css = require("text!ext/jasmine/jasmine.css");
    DIVIDER_POSITION = 2300;
    MENU_ENTRY_POSITION = 2400;
    PANEL_POSITION = 10000;
    PATH_TO_JASMINE = 'node_modules/jasmine-node/lib/jasmine-node/cli.js';
    return module.exports = ext.register('ext/jasmine/jasmine', {
      name: 'Jasmine',
      dev: 'Tobias Metzke, Tobias Pfeiffer',
      type: ext.GENERAL,
      alone: true,
      commands: {
        'jasmine': {
          hint: 'Run your tests with jasmine!'
        }
      },
      hotitems: {},
      markup: markup,
      nodes: [],
      css: css,
      hook: function() {
        var _self;
        apf.importCssString(css);
        _self = this;
        this.markupInsertionPoint = colLeft;
        panels.register(this, {
          position: PANEL_POSITION,
          caption: "Jasmine",
          "class": "jasmine"
        });
        commands.addCommand({
          name: "jasmine",
          hint: "run your specs with jasmine",
          bindKey: {
            mac: "Command-J",
            win: "Ctrl-J"
          },
          exec: function() {
            return _self.jasmine();
          }
        });
        this.nodes.push(menus.addItemByPath("Edit/~", new apf.divider(), DIVIDER_POSITION));
        this.nodes.push(menus.addItemByPath("Edit/Jasmine", new apf.item({
          command: "jasmine"
        }), MENU_ENTRY_POSITION));
        this.hotitems['jasmine'] = [this.nodes[1]];
        this.projectName = this.getProjectName();
        return this.socketListenerRegistered = false;
      },
      init: function() {
        var _self,
          _this = this;
        this.initButtons();
        this.panel = windowTestPanelJasmine;
        this.nodes.push(windowTestPanelJasmine, menuRunSettingsJasmine, stateTestRunJasmine);
        _self = this;
        dataGridTestProjectJasmine.addEventListener('afterchoose', function() {
          return _this.run(dataGridTestProjectJasmine.getSelection());
        });
        ide.dispatchEvent("init.jasmine");
        this.setRepoName();
        this.initFilelist();
        return this.afterFileSave();
      },
      initButtons: function() {
        buttonTestRunJasmine.$ext.setAttribute("class", "light-dropdown");
        buttonTestStopJasmine.$ext.setAttribute("class", buttonTestStopJasmine.$ext.getAttribute("class") + " buttonTestStopJasmine");
        return windowTestPanelJasmine.$ext.setAttribute("class", windowTestPanelJasmine.$ext.getAttribute("class") + " testpanelJasmine");
      },
      setRepoName: function() {
        this.projectName = this.getProjectName();
        return modelTestsJasmine.data.childNodes[1].setAttribute('name', this.projectName);
      },
      initFilelist: function() {
        var _this = this;
        return filelist.getFileList(false, function(data, state) {
          var sanitizedData, specs;
          if (state !== apf.SUCCESS) {
            return;
          }
          sanitizedData = data.replace(/^\./gm, "");
          sanitizedData = sanitizedData.replace(/^\/node_modules\/.*/gm, "");
          specs = sanitizedData.match(/^.*\.spec\.(js|coffee)$/gm);
          return _this.addFiles(specs, modelTestsJasmine.queryNode("repo[1]"));
        });
      },
      addFiles: function(specs, parent) {
        var xmlFiles;
        xmlFiles = "";
        specs.each(function(spec) {
          return xmlFiles += "<file path='" + apf.escapeXML(ide.davPrefix + spec) + "' name='" + apf.escapeXML(spec.split("/").pop()) + "' type='jasmine' />";
        });
        return modelTestsJasmine.insert("<files>" + xmlFiles + "</files>", {
          insertPoint: parent
        });
      },
      afterFileSave: function() {
        var _this = this;
        return ide.addEventListener('afterfilesave', function(event) {
          var name;
          name = _this.getFileNameFrom(event.node);
          return _this.runJasmine([name]);
        });
      },
      getProjectName: function() {
        return document.title.slice(0, document.title.indexOf('-') - 1);
      },
      show: function() {
        if ((navbar.current != null) && (navbar.current !== this)) {
          navbar.current.disable();
        } else {
          return;
        }
        panels.initPanel(this);
        return this.enable();
      },
      enable: function() {
        return this.nodes.each(function(item) {
          if (item.enable) {
            return item.enable();
          }
        });
      },
      disable: function() {
        return this.nodes.each(function(item) {
          if (item.disable) {
            return item.disable();
          }
        });
      },
      destroy: function() {
        this.nodes.each(function(item) {
          return item.destroy(true, true);
        });
        this.nodes = [];
        return panels.unregister(this);
      },
      getFileNameFrom: function(node) {
        var fullFileName, name;
        fullFileName = node.getAttribute('name');
        return name = fullFileName.slice(0, fullFileName.indexOf('.'));
      },
      run: function(nodes) {
        var fileNames,
          _this = this;
        console.log(nodes);
        fileNames = [];
        nodes.each(function(node) {
          var name;
          name = _this.getFileNameFrom(node);
          return fileNames.push(name);
        });
        return this.runJasmine(fileNames);
      },
      runJasmine: function(fileNames) {
        var args, matchString;
        args = ['--coffee', 'spec/'];
        if ((fileNames != null) && fileNames.length > 0) {
          matchString = '(';
          fileNames.each(function(name) {
            return matchString += name + '|';
          });
          matchString = matchString.slice(0, -1) + ')' + "\\.";
          args.push('--match', matchString);
        }
        this.message = '';
        if (!this.socketListenerRegistered) {
          this.registerSocketListener();
        }
        return noderunner.run(PATH_TO_JASMINE, args, false);
      },
      registerSocketListener: function() {
        var _this = this;
        this.message = '';
        ide.addEventListener('socketMessage', function(event) {
          if (event.message.type === 'node-data') {
            _this.assembleMessage(event.message.data);
          }
          if (event.message.type === 'node-exit') {
            return _this.parseMessage();
          }
        });
        return this.socketListenerRegistered = true;
      },
      assembleMessage: function(message) {
        return this.message += message;
      },
      parseMessage: function() {
        var failureMessages;
        failureMessages = this.message.match(/Failures:\s([\s\S]*)\n+Finished/m);
        if (failureMessages != null) {
          return this.handleFailures(failureMessages);
        } else {
          return this.allSpecsPass();
        }
      },
      handleFailures: function(failureMessages) {
        var failures,
          _this = this;
        failures = failureMessages[1].split("\n\n");
        return failures.each(function(failure) {
          return _this.parseFailure(failure);
        });
      },
      parseFailure: function(failure) {
        var errorLine, matches, message, stacktrace;
        matches = failure.match(/Message:\s([\s\S]+?)Stacktrace:[\s\S]*?(at[\s\S]*)/m);
        message = matches[1];
        stacktrace = matches[2];
        errorLine = this.parseStackTrace(stacktrace);
        return console.log(errorLine);
      },
      parseStackTrace: function(stacktrace) {
        var error, traces,
          _this = this;
        traces = stacktrace.split("\n");
        error = '';
        traces.each(function(trace) {
          if ((trace.indexOf('node_modules') === -1) && (trace.indexOf(_this.projectName) >= 0)) {
            error = trace.match(new RegExp(_this.projectName + '(.+)'))[1];
            error = error.slice(0, -1);
            return error;
          }
        });
        return error;
      },
      allSpecsPass: function() {},
      setPass: function(node, msg) {
        apf.xmldb.setAttribute(node, "status", 1);
        return apf.xmldb.setAttribute(node, "status-message", msg || "");
      },
      setError: function(node, msg) {
        apf.xmldb.setAttribute(node, "status", 0);
        return apf.xmldb.setAttribute(node, "status-message", msg || "");
      },
      jasmine: function() {
        return this.runJasmine();
      }
    });
  });

}).call(this);
