// Generated by CoffeeScript 1.3.3
(function() {
  var MessageParser;

  MessageParser = (function() {

    function MessageParser() {}

    MessageParser.prototype.isSyntaxError = function(message) {
      return message.indexOf('SyntaxError:') !== -1;
    };

    return MessageParser;

  })();

  define(function(require, exports, module) {
    return exports.MessageParser = MessageParser;
  });

}).call(this);
